bunny:
  replicaCount: 1
  image:
    repository: registry.bender-cloud.net/daily-bunny
    tag: "1.0.3"
    pullPolicy: IfNotPresent
  secret: bunny-dotfile-secret
  storage:
    size: 2Gi
    class: longhorn
    accessMode: ReadWriteMany

mongo:
  image:
    repository: mongo
    tag: "4"
    pullPolicy: IfNotPresent
  storage:
    size: 2Gi
    class: local-path

nginx:
  replicaCount: 3
  image:
    repository: nginx
    tag: "1.22.1"
    pullPolicy: IfNotPresent


ingress:
  host: bunny.bender-cloud.net
  certIssuer: letsencrypt