storage:
  size: 10Gi
  class: local-path

bunny:
  replicaCount: 1
  image:
    repository: registry.bender-cloud.net/daily-bunny
    tag: "1.0.2"
    pullPolicy: IfNotPresent
  secret: bunny-dotfile-secret

mongo:
  image:
    repository: mongo
    tag: "4"
    pullPolicy: IfNotPresent

nginx:
  replicaCount: 3
  image:
    repository: nginx
    tag: "1.22.1"
    pullPolicy: IfNotPresent


ingress:
  host: bunny.bender-cloud.net
  certIssuer: letsencrypt