apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim-multi
spec:
  accessModes:
    - {{ .Values.bunny.storage.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.bunny.storage.size }}
  storageClassName: {{ .Values.bunny.storage.class }}